[workspace]
resolver = "2"
members = [
    "crates/app",
    "crates/native",
    "crates/wasm",
    "lib/crates/assets",
    "lib/crates/audio",
    "lib/crates/ecs",
    "lib/crates/graphics",
    "lib/crates/util",
    "lib/crates/dac",
]