[header]
asset_type = "Shader"

[[properties.Shader.sources]]
kind = "Vertex"
origin.External.File = "bins/geometry.vsh"

[[properties.Shader.sources]]
kind = "Fragment"
origin.External.File = "bins/geometry.fsh"