[header]
asset_type = "Shader"

[[properties.Shader.sources]]
kind = "Vertex"
origin.External.File = "shaders/screen.vsh"

[[properties.Shader.sources]]
kind = "Fragment"
origin.External.File = "shaders/screen.fsh"