[header]
asset_type = "Font"

[properties.Font.source]
Url.url = "https://github.com/web-fonts/arial-geo/raw/refs/heads/master/fonts/arial-geo-webfont.ttf"

[properties.Font]
size = 64

[properties.Font.charset]
numbers = true
special_symbols = true
latin = false
cyrillic = false


