
#define DEBUG_MODE_OFF 0
#define DEBUG_MODE_ALBEDO 1
#define DEBUG_MODE_METALLIC 2
#define DEBUG_MODE_NORMAL 3
#define DEBUG_MODE_ROUGHNESS 4
#define DEBUG_MODE_AO 5
#define DEBUG_MODE_DEPTH 6
#define DEBUG_MODE_POSITION 7
#define DEBUG_MODE_SSAO 8
#define DEBUG_MODE_SKYBOX 9