[header]
asset_type = "Font"
author = "Roman Shamin <al4emist.artway@gmail.com>, Evil Martians <fonts@evilmartians.com>"
license = "OFL-1.1 license"

[properties.Font.source]
Url.url = "https://github.com/evilmartians/mono/raw/refs/heads/main/fonts/ttf/MartianMono-Regular.ttf"

[properties.Font]
size = 40

[properties.Font.charset]
numbers = true
special_symbols = true
latin = true
cyrillic = false


