name: Create Release

on:
  push:
      tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
    - name: Cache cargo registry
      uses: Swatinem/rust-cache@v2

    - name: Install global dependencies
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libx11-dev libgl1-mesa-dev

    - name: Get Current Git Tag
      id: get_current_tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - name: Update version in Cargo.toml
      run: cargo install cargo-edit && cargo set-version ${TAG#v}

    - name: Build
      run: cargo build --verbose --release
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-linux-x11
        path: target/release/dawn
        retention-days: 5
    - name: Upload assets artifact
      uses: actions/upload-artifact@v4
      with:
        name: assets
        path: target/release/assets.dac
        retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
    - name: Cache cargo registry
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release

    - name: Get Current Git Tag
      id: get_current_tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - name: Update version in Cargo.toml
      run: cargo install cargo-edit && cargo set-version ${TAG#v}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: target/release/dawn.exe
        retention-days: 5


  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [build-linux-x11, build-windows]
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v5
      with:
        name: build-linux-x11
    - name: Download Windows artifact
      uses: actions/download-artifact@v5
      with:
        name: build-windows
    - name: Download assets artifact
      uses: actions/download-artifact@v5
      with:
        name: assets

    - name: Get Current Git Tag
      id: get_current_tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_latest_tag.outputs.tag }}
        release_name: Release v${{ steps.get_latest_tag.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload Linux binary to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dawn-v${{ steps.get_latest_tag.outputs.tag }}-linux-x11
        asset_name: dawn-linux-x11
        asset_content_type: application/octet-stream

    - name: Upload Windows binary to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dawn-v${{ steps.get_latest_tag.outputs.tag }}-windows.exe
        asset_name: dawn-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload assets to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./assets.dac
        asset_name: assets.dac
        asset_content_type: application/octet-stream