name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal

    - name: Cache cargo registry
      uses: Swatinem/rust-cache@v2

    - name: Install global dependencies
      run: sudo apt-get update && apt-get install -y libasound2-dev

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
